spring:
  application:
    name: security-agent-service
  cloud:
    stream:
      bindings:
        security-input:
          destination: security-events
          group: security-group
        security-output:
          destination: security-events
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.futureim.generative.im.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_agent?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
