spring:
  application:
    name: design-agent-service
  cloud:
    stream:
      bindings:
        design-input:
          destination: design-events
          group: design-group
        design-output:
          destination: design-events
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.futureim.generative.im.design: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/design_agent?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
