server:
  port: 8091

spring:
  application:
    name: voice-commerce-inventory-service
  webflux:
    cors:
      allowed-origins: http://localhost:5000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers
      exposed-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
