spring:
  application:
    name: quality-agent-service
  cloud:
    stream:
      bindings:
        quality-input:
          destination: quality-events
          group: quality-group
        quality-output:
          destination: quality-events
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.futureim.generative.im.quality: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quality_agent?createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
